import { PassiveDef, PassiveType } from '../types';

export const PASSIVE_REGISTRY: Record<PassiveType, PassiveDef> = {
  magnet: {
    id: 'magnet',
    name: 'Vacuum Magnet',
    nameAr: 'مغناطيس الجواهر',
    description: 'Increases the attraction radius for collecting XP gems from further away.',
    descriptionAr: 'يزيد نطاق سحب وامتصاص جواهر الخبرة من مسافات بعيدة.',
    icon: 'Magnet',
    maxLevel: 5,
    perLevelBonus: '+40% Pickup Radius',
    perLevelBonusAr: '+40% نطاق جذب الجواهر',
  },
  swift_boots: {
    id: 'swift_boots',
    name: 'Swift Boots',
    nameAr: 'أحذية السرعة',
    description: 'Increases player movement speed to dodge fast swarms.',
    descriptionAr: 'يزيد سرعة حركة اللاعب لتفادي هجمات جحافل الوحوش ومحاصرتها.',
    icon: 'Footprints',
    maxLevel: 5,
    perLevelBonus: '+12% Move Speed',
    perLevelBonusAr: '+12% سرعة الحركة',
  },
  might: {
    id: 'might',
    name: 'Might Emblem',
    nameAr: 'شعار القوة',
    description: 'Increases the overall damage dealt by all equipped weapons.',
    descriptionAr: 'يزيد قوة الضرر لكافة أسلحتك بنسبة تصاعدية.',
    icon: 'Swords',
    maxLevel: 5,
    perLevelBonus: '+18% Total Damage',
    perLevelBonusAr: '+18% زيادة الضرر الشامل',
  },
  vitality: {
    id: 'vitality',
    name: 'Dragon Vitality',
    nameAr: 'حيوية التنين',
    description: 'Increases maximum Health Points and enables health regeneration.',
    descriptionAr: 'يزيد الحد الأقصى للصحة مع تفعيل التجديد التلقائي لدمك باستمرار.',
    icon: 'HeartPulse',
    maxLevel: 5,
    perLevelBonus: '+25 Max HP & +0.8 HP/sec',
    perLevelBonusAr: '+25 أقصى صحة وتجديد 0.8 دم/ثانية',
  },
  armor: {
    id: 'armor',
    name: 'Iron Plate',
    nameAr: 'الدرع الفولاذي',
    description: 'Reduces damage received from enemy collisions and strikes.',
    descriptionAr: 'يقلل مقدار الضرر المتلقى من اصطدام وضربات الوحوش.',
    icon: 'Shield',
    maxLevel: 5,
    perLevelBonus: '-2 Damage Taken & +5% Damage Resistance',
    perLevelBonusAr: '-2 تخفيض الضرر المتلقى و+5% مقاومة',
  },
  haste: {
    id: 'haste',
    name: 'Chrono Haste',
    nameAr: 'تسارع الزمن',
    description: 'Decreases the cooldown interval of all active weapon attacks.',
    descriptionAr: 'يقلل وقت انتظار هجمات جميع الأسلحة لإطلاق مستمر وأسرع.',
    icon: 'Hourglass',
    maxLevel: 5,
    perLevelBonus: '-10% Weapon Cooldown',
    perLevelBonusAr: '-10% تقليل وقت انتظار الهجوم',
  },
};
